version: '3'
services:

  apache:
    image: php:7.4.5-apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - "./mysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    links:
      - "mysql:db"
